src/model/users/views.py
from flask import Blueprint, request, session, url_for, render_template, jsonify
from werkzeug.utils import redirect
from src.model.users.user import User, Token, Private
from src.model.users.token_response import TokenResponse
from src.model.users.private_response import PrivateResponse
import src.model.users.errors as UserErrors
import src.model.users.constants as UserConstants
import src.model.users.decorators as user_decorators
from flask_jwt_extended import (JWTManager, jwt_required, create_access_token, create_refresh_token,
                                jwt_refresh_token_required, get_jwt_identity)
from src.model.users.security import login_user_app_security

user_blueprint = Blueprint('users', __name__)


@user_blueprint.route('/login', methods=['GET', 'POST'])
def login_user():
    if request.method == 'POST':
        email = request.form[UserConstants.EMAIL]
        password = request.form[UserConstants.PASSWORD]
        try:
            if User.is_login_valid(email, password):
                session[UserConstants.EMAIL] = email
                print(session['email'])
                if email == "admin@intelgeo.net":
                    return redirect(url_for('home.intelgeo'))
                if email == "ceac@cns.gob.mx":
                    return redirect(url_for('home.luciad'))
                if email == 's.morales@intelgeo.net':
                    return redirect(url_for('home.user'))
                if email == 'j.molina@intelgeo.net':
                    return redirect(url_for('home.supervisor'))
                if email == 'dev@intelgeo.net':
                    return  redirect(url_for('home.index'))
        except UserErrors.UserError as e:
            return render_template('login.html')
    return render_template('login.html')  # Manda un error por al usuario


@user_blueprint.route('/login_app', methods=['GET', 'POST'])
def login_user_app():
    if request.method == 'POST':
        recive = request.get_json()
        json = login_user_app_security(recive)
        if json['status']:
            access_token = create_access_token(identity=json['user'])
            return jsonify({"access_token": access_token}), 202
        else:
            return jsonify({"access_token": json['msg']}), 202


@user_blueprint.route('/singup', methods=['GET', 'POST'])
def register_user():
    if request.method == 'POST':
        email = request.form[UserConstants.EMAIL]
        password = request.form[UserConstants.PASSWORD]
        token = request.form[UserConstants.TOKEN]
        user_agent = str(request.user_agent)
        try:
            if User.register_user(email, password, token, user_agent):
                Token.register_app_token(email, "denegar", "denegar", "denegar")
                return redirect(url_for('.login_user'))
        except UserErrors.UserError as e:
            return e.message

    return render_template('users/singup.html')  # Manda un error por al usuario


@user_blueprint.route('/register_device', methods=['POST'])
# @user_decorators.request_login
def register_user_device():
    json = request.get_json()
    application = json[UserConstants.APPLICATION]
    token = json[UserConstants.TOKEN]
    email = json[UserConstants.EMAIL]
    password = json[UserConstants.PASSWORD]
    tokendevice = json[UserConstants.TOKEN_DEVICE]
    user_agent = str(request.user_agent)
    try:
        if User.register_user_device(application, token, email, password, tokendevice, user_agent):
            return jsonify({"msg": "Correcto"}), 200
    except UserErrors.UserError as e:
        return e.message


@user_blueprint.route('/register_token', methods=['POST'])
# @user_decorators.request_login
def register_app_token():
    json = request.get_json()
    email = json[UserConstants.EMAIL]
    alert = json[UserConstants.ALERTAPP]
    questionary = json[UserConstants.QUESTIONARYAPP]
    confirm = json[UserConstants.CONFIRMAPP]
    try:
        if Token.register_app_token(email, alert, questionary, confirm):
            return jsonify({"msg": "registrado correctamente"}), 200
    except UserErrors.UserError as e:
        return e.message


@user_blueprint.route('/token_status', methods=['GET'])
# @user_decorators.request_login
def consult_token_status():
    return jsonify(TokenResponse(Token.all()).tokenJsonResponse()), 202


@user_blueprint.route('/get_token', methods=['POST'])
# @user_decorators.request_login
def get_token():
    json = request.get_json()
    email = json[UserConstants.EMAIL]
    try:
        return jsonify(Token.get_token(email)), 202
    except UserErrors.UserError as e:
        return e.message


@user_blueprint.route('/get_status', methods=['POST'])
def get_status():
    json = request.get_json()
    tokendevice = json[UserConstants.TOKEN_DEVICE]
    app = json["app"]
    return jsonify(User.get_status(tokendevice, app))


@user_blueprint.route('/curp_status', methods=['GET'])
# @user_decorators.request_login
def consult_registered_curp():
    return jsonify(PrivateResponse(Private.all()).privateJsonResponse()), 202


@user_blueprint.route('/register_curp', methods=['POST'])
# @user_decorators.request_login
def register_curp():
    email = request.form[UserConstants.EMAIL]
    curp = session.get(UserConstants.EMAIL, 'not set')
    try:
        if Private.register_curp(email, curp):
            return jsonify({"msg": "registrado correctamente"}), 202
    except UserErrors.UserError as e:
        return e.message


@user_blueprint.route('/logout')
def logout_user():
    session['email'] = None
    return redirect(url_for('.login_user'))

templates/base_login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Olly</title>
    {% include 'html_dependencies_login.html' %}
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

templates/html_dependencies_login.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
<link rel="stylesheet" href="{{ url_for('static', filename = 'css/style.css')}}">
<meta name="viewport" content="width=device-width, initial-scale=1">

<!--===============================================================================================-->
<!--===============================================================================================-->
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="../static/images/icons/favi.ico"/>
<!--===============================================================================================-->

<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../static/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../static/fonts/iconic/css/material-design-iconic-font.min.css">
<!--===============================================================================================-->

<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../static/css/util.css">
	<link rel="stylesheet" type="text/css" href="../static/css/main.css">
        <link rel="stylesheet" type="text/css" href="../static/css/custom.css">
<!--===============================================================================================-->
<script src="../static/web/samples/lib/jquery/jquery-1.12.2.min.js" type="text/javascript"></script>
<script type="text/javascript" src="https://cdn.ywxi.net/js/1.js" async></script>
<!--===============================================================================================-->
<!--===============================================================================================-->

templates/login.html
{% extends "base_login.html" %}
{% block content %}
	<div class="limiter">
		<div class="container-login100" style="background-image: url('../static/images/bg-01.jpg');">
			<div class="wrap-login100">
                            <!--===============================================================================================-->
				<form id="formLogin" class="login100-form validate-form" action="{{url_for ('users.login_user')}}" method="post">
				  <span class="login100-form-logo"> <img src="../static/images/olly_web.png" width="150" height="90" alt=""/></em> </span>
                                  <span class="login100-form-title p-b-22 p-t-22"> Iniciar sesión </span>

				  <div class="wrap-input100 validate-input" data-validate = "Nombre de usuario incorrecto">
						<input class="input100" type="text" name="email" placeholder="Email">
						<span class="focus-input100" data-placeholder="&#xf207;"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="Contraseña incorrecta">
						<input class="input100" type="password" name="password" placeholder="Contraseña">
						<span class="focus-input100" data-placeholder="&#xf191;"></span>
					</div>

					<div class="contact100-form-checkbox">
						<input class="input-checkbox100" id="ckb1" type="checkbox" name="remember-me">
						<label class="label-checkbox100" for="ckb1">
							Recordarme
						</label>
					</div>

					<div class="container-login100-form-btn">
						<button type = "submit" class="login100-form-btn">
							Entrar
						</button>
					</div>
					<div class="text-center p-t-12">
						<a href="{{ url_for('users.register_user')}}">Registrarse</a>
					</div>
				</form>
			</div>
		</div>
	</div>

	<div id="dropDownSelect1"></div>

{% endblock %}